"""LIRL receipt-parity tests — Python organism_receipt vs Sovereign-X Node adapter.

Contract: identical LIRL stored evidence must yield byte-identical canonical JSON
and identical receipt ids from Node (src/lirl/organismReceipt.js in
Sovereign-X) and Python (src/organism_receipt.py). Golden ids below were
generated by the Node adapter and are asserted without requiring node; the
live cross-check runs against the working clone when present.
"""

from __future__ import annotations

import json
import os
import subprocess
import unittest
from pathlib import Path

from src.organism_receipt import (
    canonical_json,
    from_lirl,
    validate_organism_receipt,
    verify_receipt_id,
)

SOVEREIGN_X_RECEIPT_JS = Path(
    "/home/jon/dev/Sovereign-X/src/lirl/organismReceipt.js"
)

GOLDEN_IDS = {
    "accept_full": "org:2595ab1c4f6860a3df7802cab9a04fc3d27637d098cd69fc07322d0e82376154",
    "reject_anonymous": "org:c4336f58a61b1bef8ead09c9b2f6c4d347b77dfb7aada40be2d8106d1192548d",
    "unicode_reasons": "org:5bd3ffa0292d2ce093930153dd23ba35e4faaf4c51ee2c50bab39229ea151cbd",
    "minimal_empty": "org:143906fb50cc524cdf4e6e72e8ebffb6bd07d43b38b6871d5b99dfe886833b6d",
}

CANONICAL_UNICODE_GOLDEN = '{"a":[1,{"k":"v"}],"n":null,"z":"ünïcode ✓"}'

PARITY_VECTORS: dict[str, dict] = {
    "accept_full": {
        "receiptId": "evidence:fd794caedeadbeef",
        "issuedAt": "2026-08-23T12:00:00Z",
        "verdict": "ACCEPT",
        "intentId": "intent-1",
        "actorId": "operator",
        "action": "memory.write",
        "memoryWritten": True,
        "reasons": ["actor lawful", "action in allowlist"],
        "claimLabel": "lirl:accept:memory.write",
        "subsystem": "lirl-vertical-slice",
        "subjectHash": "a" * 64,
        "evidenceRefs": ["intent-1", "run-1", "span-1"],
        "sequence": 7,
    },
    "reject_anonymous": {
        "receiptId": "",
        "issuedAt": "2026-08-23T12:00:01Z",
        "verdict": "REJECT",
        "intentId": "intent-2",
        "actorId": "anonymous",
        "action": "rm.rf.all",
        "memoryWritten": False,
        "reasons": ["anonymous actor is not lawful under LIRL", "action not in allowlist"],
        "claimLabel": "lirl:reject:rm.rf.all",
        "subsystem": "lirl-vertical-slice",
        "subjectHash": None,
        "evidenceRefs": [],
        "sequence": 0,
    },
    "unicode_reasons": {
        "receiptId": "evidence:cafe",
        "issuedAt": "2026-08-23T12:00:02Z",
        "verdict": "ACCEPT",
        "intentId": "intent-3",
        "actorId": "governance",
        "action": "mémoire.write ✓",
        "memoryWritten": True,
        "reasons": ["loi respectée — ⚖"],
        "claimLabel": "lirl:accept:unicode",
        "subsystem": "système-organisme",
        "subjectHash": "b" * 64,
        "evidenceRefs": ["réf-ünïcode"],
        "sequence": 42,
    },
    "minimal_empty": {
        "issuedAt": "2026-08-23T12:00:03Z",
        "verdict": "REJECT",
        "reasons": [],
        "memoryWritten": False,
    },
}


class TestGoldenReceiptIds(unittest.TestCase):
    """Python adapter must reproduce Node-issued receipt ids exactly."""

    def test_all_vectors_match_node_golden_ids(self):
        for name, stored in PARITY_VECTORS.items():
            with self.subTest(vector=name):
                receipt = from_lirl(stored)
                self.assertEqual(receipt["receipt_id"], GOLDEN_IDS[name])

    def test_golden_receipts_validate_and_are_tamper_evident(self):
        for name, stored in PARITY_VECTORS.items():
            with self.subTest(vector=name):
                receipt = from_lirl(stored)
                valid, errors = validate_organism_receipt(receipt)
                self.assertTrue(valid, errors)
                self.assertTrue(verify_receipt_id(receipt))
                mutated = dict(receipt)
                mutated["effect"] = dict(receipt["effect"], performed=not receipt["effect"]["performed"])
                self.assertFalse(verify_receipt_id(mutated))

    def test_refusal_receipt_is_first_class(self):
        receipt = from_lirl(PARITY_VECTORS["reject_anonymous"])
        valid, errors = validate_organism_receipt(receipt)
        self.assertTrue(valid, errors)  # refusal documents an unlawful attempt lawfully
        self.assertEqual(receipt["decision"]["outcome"], "reject")
        self.assertEqual(receipt["replay"]["packet_hash"], "")  # empty receiptId -> empty packet hash

    def test_empty_optional_fields_hash_canonical_empty_values(self):
        """Parity regression: null/missing subjectHash hashes '""' like the Node
        adapter — it must not collapse to the empty string."""
        receipt = from_lirl(PARITY_VECTORS["minimal_empty"])
        expected_empty_string_digest = __import__("hashlib").sha256(b'""').hexdigest()
        self.assertEqual(receipt["intent"]["text_digest"], expected_empty_string_digest)
        expected_empty_list_digest = __import__("hashlib").sha256(b"[]").hexdigest()
        self.assertEqual(receipt["evidence"]["response_digest"], expected_empty_list_digest)


class TestCanonicalJsonParity(unittest.TestCase):
    def test_unicode_nested_sorted_keys(self):
        value = {"z": "ünïcode ✓", "a": [1, {"k": "v"}], "n": None}
        self.assertEqual(canonical_json(value), CANONICAL_UNICODE_GOLDEN)

    def test_live_cross_check_against_sovereign_x_source(self):
        if not SOVEREIGN_X_RECEIPT_JS.is_file():
            self.skipTest(f"Sovereign-X clone not mounted: {SOVEREIGN_X_RECEIPT_JS}")
        for name, stored in PARITY_VECTORS.items():
            with self.subTest(vector=name):
                script = (
                    f"import {{ fromLirl }} from '{SOVEREIGN_X_RECEIPT_JS}';\n"
                    f"const stored = {json.dumps(stored)};\n"
                    "console.log(fromLirl(stored).receipt_id);\n"
                )
                out = subprocess.run(
                    ["node", "--input-type=module", "-e", script],
                    capture_output=True,
                    text=True,
                    timeout=60,
                )
                if out.returncode != 0:
                    self.fail(f"node adapter failed: {out.stderr[:300]}")
                self.assertEqual(out.stdout.strip(), from_lirl(stored)["receipt_id"])


if __name__ == "__main__":
    unittest.main()
